version: 2
jobs:
  build:
    docker:
      - image: quay.io/cybozu/golang:1.13-bionic
    working_directory: /work
    steps:
      - checkout
      - run: make test
      - run: make install GOBIN=/tmp/workspace
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - setup-hw
            - monitor-hw
            - collector
  build-image:
    working_directory: /app
    docker:
      - image: docker:stable
    steps:
      - run:
          name: Install tools
          command: |
            apk add --no-cache git
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Copy binaries
          command: |
            cp /tmp/workspace/setup-hw docker
            cp /tmp/workspace/monitor-hw docker
            cp /tmp/workspace/collector docker
      - setup_remote_docker
      - run:
          name: Build images
          command: |
            docker build -t quay.io/cybozu/setup-hw:latest --target stage1 docker
            docker build -t quay.io/cybozu/setup-hw-secret:latest docker
      - run:
          name: Save images
          command: |
            mkdir -p /tmp/docker
            docker save quay.io/cybozu/setup-hw:latest -o /tmp/docker/setup-hw-image
            docker save quay.io/cybozu/setup-hw-secret:latest -o /tmp/docker/setup-hw-secret-image
      - persist_to_workspace:
          root: /tmp/docker
          paths:
            - setup-hw-image
            - setup-hw-secret-image
  push-image:
    docker:
      - image: docker:stable
    steps:
      - attach_workspace:
          at: /tmp/docker
      - setup_remote_docker
      - run:
          name: Load images
          command: |
            docker load -i /tmp/docker/setup-hw-image
            docker load -i /tmp/docker/setup-hw-secret-image
      - run:
          name: Push images to Quay.io
          command: |
            docker login -u $QUAY_USER -p $QUAY_PASSWORD quay.io
            TAG=$(echo $CIRCLE_TAG | cut -c 2-)
            for name in setup-hw setup-hw-secret; do
                echo "pushing ${name} ..."
                docker tag quay.io/cybozu/${name}:latest quay.io/cybozu/${name}:$TAG
                docker push quay.io/cybozu/${name}:latest
                docker push quay.io/cybozu/${name}:$TAG
            done

workflows:
  version: 2
  main:
    jobs:
      - build
      - build-image:
          requires:
            - build
  release:
    jobs:
      - build:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
      - build-image:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
      - push-image:
          requires:
            - build-image
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
