// Code generated by render-rules.  DO NOT EDIT.
//go:generate go run ../pkg/render-rules

package redfish

import (
	"log"
)

func init() {
	for _, rule := range Rules {
		if err := rule.Compile(); err != nil {
			log.Fatal(err)
		}
	}
}

var Rules = map[string]*CollectRule{
	"dell_redfish_1.0.2.yml": {
		TraverseRule: traverseRule{
			Root: "/redfish/v1",
			ExcludeRules: []string{
				"/JSONSchemas",
				"/Accounts",
				"/Certificates",
				"/Jobs",
				"/Logs",
				"/Registries",
				"/Roles",
				"/Sessions",
				"/AccountService",
				"/EventService",
				"/LogServices",
				"/SessionService",
				"/TaskService",
				"/UpdateService",
				"/Power/",
				"/Sensors/",
				"/Thermal/",
				"/redfish/v1/Chassis/$",
			},
		},
		MetricRules: []*metricRule{
			{
				Path: "/redfish/v1/Chassis/{chassis}",
				PropertyRules: []*propertyRule{
					{
						Pointer: "/Status/Health",
						Name:    "chassis_status_health",
						Help:    "",
						Type:    "health",
					},
				},
			},
			{
				Path: "/redfish/v1/Chassis/{chassis}/Power",
				PropertyRules: []*propertyRule{
					{
						Pointer: "/PowerSupplies/{psu}/Status/Health",
						Name:    "chassis_psu_status_health",
						Help:    "",
						Type:    "health",
					},
					{
						Pointer: "/Redundancy/{set}/Status/Health",
						Name:    "chassis_psu_redundancy_status_health",
						Help:    "",
						Type:    "health",
					},
					{
						Pointer: "/Voltages/{sensor}/Status/Health",
						Name:    "chassis_voltage_status_health",
						Help:    "",
						Type:    "health",
					},
				},
			},
			{
				Path: "/redfish/v1/Chassis/{chassis}/Thermal",
				PropertyRules: []*propertyRule{
					{
						Pointer: "/Fans/{fan}/Status/Health",
						Name:    "chassis_fan_status_health",
						Help:    "",
						Type:    "health",
					},
					{
						Pointer: "/Redundancy/{set}/Status/Health",
						Name:    "chassis_fan_redundancy_status_health",
						Help:    "",
						Type:    "health",
					},
					{
						Pointer: "/Temperatures/{sensor}/Status/Health",
						Name:    "chassis_temperature_status_health",
						Help:    "",
						Type:    "health",
					},
					{
						Pointer: "/Temperatures/{sensor}/ReadingCelsius",
						Name:    "chassis_temperature_reading",
						Help:    "",
						Type:    "number",
					},
				},
			},
			{
				Path: "/redfish/v1/Systems/{system}",
				PropertyRules: []*propertyRule{
					{
						Pointer: "/Status/Health",
						Name:    "system_status_health",
						Help:    "",
						Type:    "health",
					},
					{
						Pointer: "/MemorySummary/Status/Health",
						Name:    "system_memory_summary_status_health",
						Help:    "",
						Type:    "health",
					},
					{
						Pointer: "/ProcessorSummary/Status/Health",
						Name:    "system_processor_summary_status_health",
						Help:    "",
						Type:    "health",
					},
					{
						Pointer: "/TrustedModules/{tpm}/Status/State",
						Name:    "system_tpm_status_state",
						Help:    "",
						Type:    "state",
					},
				},
			},
			{
				Path: "/redfish/v1/Systems/{system}/EthernetInterfaces/{interface}",
				PropertyRules: []*propertyRule{
					{
						Pointer: "/Status/Health",
						Name:    "network_status_health",
						Help:    "",
						Type:    "health",
					},
				},
			},
			{
				Path: "/redfish/v1/Systems/{system}/Processors/{processor}",
				PropertyRules: []*propertyRule{
					{
						Pointer: "/Status/Health",
						Name:    "processor_status_health",
						Help:    "",
						Type:    "health",
					},
				},
			},
			{
				Path: "/redfish/v1/Systems/{system}/Storage/Controllers/{controller}",
				PropertyRules: []*propertyRule{
					{
						Pointer: "/Status/Health",
						Name:    "storage_controller_status_health",
						Help:    "",
						Type:    "health",
					},
					{
						Pointer: "/Devices/{device}/Status/Health",
						Name:    "storage_device_status_health",
						Help:    "",
						Type:    "health",
					},
				},
			},
			{
				Path: "/redfish/v1/Managers/{manager}",
				PropertyRules: []*propertyRule{
					{
						Pointer: "/Status/Health",
						Name:    "manager_status_health",
						Help:    "",
						Type:    "health",
					},
				},
			},
			{
				Path: "/redfish/v1/Managers/{manager}/EthernetInterfaces/{interface}",
				PropertyRules: []*propertyRule{
					{
						Pointer: "/Status/Health",
						Name:    "manager_network_status_health",
						Help:    "",
						Type:    "health",
					},
				},
			},
		},
	},
	"dell_redfish_1.2.0.yml": {
		TraverseRule: traverseRule{
			Root: "/redfish/v1",
			ExcludeRules: []string{
				"/JSONSchemas",
				"/Accounts",
				"/Certificates",
				"/Jobs",
				"/Logs",
				"/Registries",
				"/Roles",
				"/Sessions",
				"/AccountService",
				"/EventService",
				"/LogServices",
				"/SessionService",
				"/TaskService",
				"/UpdateService",
				"/Power/",
				"/Sensors/",
				"/Thermal/",
				"/redfish/v1/Chassis/$",
			},
		},
		MetricRules: []*metricRule{
			{
				Path: "/redfish/v1/Chassis/{chassis}",
				PropertyRules: []*propertyRule{
					{
						Pointer: "/Status/Health",
						Name:    "chassis_status_health",
						Help:    "",
						Type:    "health",
					},
				},
			},
			{
				Path: "/redfish/v1/Chassis/{chassis}/Power",
				PropertyRules: []*propertyRule{
					{
						Pointer: "/PowerSupplies/{psu}/Status/Health",
						Name:    "chassis_psu_status_health",
						Help:    "",
						Type:    "health",
					},
					{
						Pointer: "/Redundancy/{set}/Status/Health",
						Name:    "chassis_psu_redundancy_status_health",
						Help:    "",
						Type:    "health",
					},
					{
						Pointer: "/Voltages/{sensor}/Status/Health",
						Name:    "chassis_voltage_status_health",
						Help:    "",
						Type:    "health",
					},
				},
			},
			{
				Path: "/redfish/v1/Chassis/{chassis}/Thermal",
				PropertyRules: []*propertyRule{
					{
						Pointer: "/Fans/{fan}/Status/Health",
						Name:    "chassis_fan_status_health",
						Help:    "",
						Type:    "health",
					},
					{
						Pointer: "/Redundancy/{set}/Status/Health",
						Name:    "chassis_fan_redundancy_status_health",
						Help:    "",
						Type:    "health",
					},
					{
						Pointer: "/Temperatures/{sensor}/Status/Health",
						Name:    "chassis_temperature_status_health",
						Help:    "",
						Type:    "health",
					},
					{
						Pointer: "/Temperatures/{sensor}/ReadingCelsius",
						Name:    "chassis_temperature_reading",
						Help:    "",
						Type:    "number",
					},
				},
			},
			{
				Path: "/redfish/v1/Systems/{system}",
				PropertyRules: []*propertyRule{
					{
						Pointer: "/Status/Health",
						Name:    "system_status_health",
						Help:    "",
						Type:    "health",
					},
					{
						Pointer: "/MemorySummary/Status/Health",
						Name:    "system_memory_summary_status_health",
						Help:    "",
						Type:    "health",
					},
					{
						Pointer: "/ProcessorSummary/Status/Health",
						Name:    "system_processor_summary_status_health",
						Help:    "",
						Type:    "health",
					},
					{
						Pointer: "/TrustedModules/{tpm}/Status/State",
						Name:    "system_tpm_status_state",
						Help:    "",
						Type:    "state",
					},
				},
			},
			{
				Path: "/redfish/v1/Systems/{system}/EthernetInterfaces/{interface}",
				PropertyRules: []*propertyRule{
					{
						Pointer: "/Status/Health",
						Name:    "network_status_health",
						Help:    "",
						Type:    "health",
					},
				},
			},
			{
				Path: "/redfish/v1/Systems/{system}/Processors/{processor}",
				PropertyRules: []*propertyRule{
					{
						Pointer: "/Status/Health",
						Name:    "processor_status_health",
						Help:    "",
						Type:    "health",
					},
				},
			},
			{
				Path: "/redfish/v1/Systems/{system}/Storage/{controller}",
				PropertyRules: []*propertyRule{
					{
						Pointer: "/Status/Health",
						Name:    "storage_controller_status_health",
						Help:    "",
						Type:    "health",
					},
				},
			},
			{
				Path: "/redfish/v1/Systems/{system}/Storage/Drives/{device}",
				PropertyRules: []*propertyRule{
					{
						Pointer: "/Status/Health",
						Name:    "storage_device_status_health",
						Help:    "",
						Type:    "health",
					},
				},
			},
			{
				Path: "/redfish/v1/Managers/{manager}",
				PropertyRules: []*propertyRule{
					{
						Pointer: "/Status/Health",
						Name:    "manager_status_health",
						Help:    "",
						Type:    "health",
					},
				},
			},
			{
				Path: "/redfish/v1/Managers/{manager}/EthernetInterfaces/{interface}",
				PropertyRules: []*propertyRule{
					{
						Pointer: "/Status/Health",
						Name:    "manager_network_status_health",
						Help:    "",
						Type:    "health",
					},
				},
			},
		},
	},
	"dell_redfish_1.4.0.yml": {
		TraverseRule: traverseRule{
			Root: "/redfish/v1",
			ExcludeRules: []string{
				"/JSONSchemas",
				"/Accounts",
				"/Certificates",
				"/Jobs",
				"/Logs",
				"/Registries",
				"/Roles",
				"/Sessions",
				"/AccountService",
				"/EventService",
				"/LogServices",
				"/SessionService",
				"/TaskService",
				"/UpdateService",
				"/Power/",
				"/Sensors/",
				"/Thermal/",
				"/redfish/v1/Chassis/$",
			},
		},
		MetricRules: []*metricRule{
			{
				Path: "/redfish/v1/Chassis/{chassis}",
				PropertyRules: []*propertyRule{
					{
						Pointer: "/Status/Health",
						Name:    "chassis_status_health",
						Help:    "",
						Type:    "health",
					},
				},
			},
			{
				Path: "/redfish/v1/Chassis/{chassis}/Power",
				PropertyRules: []*propertyRule{
					{
						Pointer: "/PowerSupplies/{psu}/Status/Health",
						Name:    "chassis_psu_status_health",
						Help:    "",
						Type:    "health",
					},
					{
						Pointer: "/Redundancy/{set}/Status/Health",
						Name:    "chassis_psu_redundancy_status_health",
						Help:    "",
						Type:    "health",
					},
					{
						Pointer: "/Voltages/{sensor}/Status/Health",
						Name:    "chassis_voltage_status_health",
						Help:    "",
						Type:    "health",
					},
				},
			},
			{
				Path: "/redfish/v1/Chassis/{chassis}/Thermal",
				PropertyRules: []*propertyRule{
					{
						Pointer: "/Fans/{fan}/Status/Health",
						Name:    "chassis_fan_status_health",
						Help:    "",
						Type:    "health",
					},
					{
						Pointer: "/Redundancy/{set}/Status/Health",
						Name:    "chassis_fan_redundancy_status_health",
						Help:    "",
						Type:    "health",
					},
					{
						Pointer: "/Temperatures/{sensor}/Status/Health",
						Name:    "chassis_temperature_status_health",
						Help:    "",
						Type:    "health",
					},
					{
						Pointer: "/Temperatures/{sensor}/ReadingCelsius",
						Name:    "chassis_temperature_reading",
						Help:    "",
						Type:    "number",
					},
				},
			},
			{
				Path: "/redfish/v1/Systems/{system}",
				PropertyRules: []*propertyRule{
					{
						Pointer: "/Status/Health",
						Name:    "system_status_health",
						Help:    "",
						Type:    "health",
					},
					{
						Pointer: "/MemorySummary/Status/Health",
						Name:    "system_memory_summary_status_health",
						Help:    "",
						Type:    "health",
					},
					{
						Pointer: "/ProcessorSummary/Status/Health",
						Name:    "system_processor_summary_status_health",
						Help:    "",
						Type:    "health",
					},
					{
						Pointer: "/TrustedModules/{tpm}/Status/State",
						Name:    "system_tpm_status_state",
						Help:    "",
						Type:    "state",
					},
				},
			},
			{
				Path: "/redfish/v1/Systems/{system}/EthernetInterfaces/{interface}",
				PropertyRules: []*propertyRule{
					{
						Pointer: "/Status/Health",
						Name:    "network_status_health",
						Help:    "",
						Type:    "health",
					},
				},
			},
			{
				Path: "/redfish/v1/Systems/{system}/Processors/{processor}",
				PropertyRules: []*propertyRule{
					{
						Pointer: "/Status/Health",
						Name:    "processor_status_health",
						Help:    "",
						Type:    "health",
					},
				},
			},
			{
				Path: "/redfish/v1/Systems/{system}/Storage/{controller}",
				PropertyRules: []*propertyRule{
					{
						Pointer: "/Status/Health",
						Name:    "storage_controller_status_health",
						Help:    "",
						Type:    "health",
					},
				},
			},
			{
				Path: "/redfish/v1/Systems/{system}/Storage/Drives/{device}",
				PropertyRules: []*propertyRule{
					{
						Pointer: "/Status/Health",
						Name:    "storage_device_status_health",
						Help:    "",
						Type:    "health",
					},
				},
			},
			{
				Path: "/redfish/v1/Managers/{manager}",
				PropertyRules: []*propertyRule{
					{
						Pointer: "/Status/Health",
						Name:    "manager_status_health",
						Help:    "",
						Type:    "health",
					},
				},
			},
			{
				Path: "/redfish/v1/Managers/{manager}/EthernetInterfaces/{interface}",
				PropertyRules: []*propertyRule{
					{
						Pointer: "/Status/Health",
						Name:    "manager_network_status_health",
						Help:    "",
						Type:    "health",
					},
				},
			},
		},
	},
	"qemu.yml": {
		TraverseRule: traverseRule{
			Root:         "/redfish/v1",
			ExcludeRules: []string{},
		},
		MetricRules: []*metricRule{
			{
				Path: "/redfish/v1/Systems/{system}/Processors/{processor}",
				PropertyRules: []*propertyRule{
					{
						Pointer: "/Status/Health",
						Name:    "processor_status_health",
						Help:    "",
						Type:    "health",
					},
				},
			},
			{
				Path: "/redfish/v1/Systems/{system}/Storage/{controller}",
				PropertyRules: []*propertyRule{
					{
						Pointer: "/Status/Health",
						Name:    "storage_controller_status_health",
						Help:    "",
						Type:    "health",
					},
				},
			},
		},
	},
}
