name: Main
on:
  pull_request:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'
jobs:
  build:
    name: build
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - run: make test
      - run: make install GOBIN=/tmp/
      - name: Upload binaries for setup-hw
        uses: actions/upload-artifact@v2
        with:
          name: setup-hw-binaries
          path: |
            /tmp/setup-hw
            /tmp/monitor-hw
            /tmp/collector
          retention-days: 1
  build_image:
    name: build_image
    needs: build
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Download binaries for setup-hw
        uses: actions/download-artifact@v2
        with:
          name: setup-hw-binaries
      - run: |
          cp setup-hw docker
          cp monitor-hw docker
          cp collector docker
      - run: |
          docker build -t quay.io/cybozu/setup-hw:latest --target stage1 docker
          docker build -t quay.io/cybozu/setup-hw-secret:latest docker
      - run: |
          mkdir -p /tmp/docker
          docker save quay.io/cybozu/setup-hw:latest -o /tmp/docker/setup-hw-image
          docker save quay.io/cybozu/setup-hw-secret:latest -o /tmp/docker/setup-hw-secret-image
      - name: Upload setup-hw images
        uses: actions/upload-artifact@v2
        with:
          name: setup-hw-images
          path: |
            /tmp/docker/setup-hw-image
            /tmp/docker/setup-hw-secret-image
          retention-days: 1
  push_image:
    name: push_image
    runs-on: ubuntu-20.04
    steps:
      - name: Push images to  if tagged
        if: startsWith( github.ref, 'refs/tags/v' )
        env:
          REF: ${{ github.ref }}
          QUAY_USER: ${{ secrets.QUAY_USER }}
          QUAY_PASSWORD: ${{ secrets.QUAY_PASSWORD }}
        uses: actions/download-artifact@v2
        with:
          name: setup-hw-images
        run: |
          docker login -u $QUAY_USER -p $QUAY_PASSWORD quay.io
          TAG=${GITHUB_REF#refs/*/}
          for name in setup-hw setup-hw-secret; do
              echo "pushing ${name} ..."
              docker tag quay.io/cybozu/${name}:latest quay.io/cybozu/${name}:$TAG
              docker push quay.io/cybozu/${name}:latest
              docker push quay.io/cybozu/${name}:$TAG
          done
